# Generated by Django 3.0.5 on 2020-05-02 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('captainicc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'verbose_name': 'Membre'},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name_plural': 'Pays'},
        ),
        migrations.AddField(
            model_name='membre',
            name='mb_created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='mb_categoryMembres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='captainicc.CategoryMembre', verbose_name='Type de Membre'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='mb_photo',
            field=models.ImageField(default='default-avatar.png', upload_to='profiles_img', verbose_name='Photo de profile'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='v_pays',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='captainicc.Pays', verbose_name='Pays'),
        ),
    ]
