# Generated by Django 3.0.5 on 2020-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captainicc', '0002_auto_20200502_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresdepartement',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de  creation'),
        ),
    ]
